### ISSUE TITLE
[Feature Request] Pull-request decoration with telemetry data could be dark-mode friendly

### ISSUE THREAD

**Issue by ubiratansoares** [thundra-io/workflow-telemetry-action#6]
Hi Thundra devs! 👋

First of all : awesome job on this Action, I'm already using it in a project and loving it ♥️

Unfortunately I'm one of those dark-mode addicted Devs (😂) and I realized that the charts plotted in the PR comment driven by this GHA don't look super-great outside the "white" theme in Github, eg

![image](https://user-images.githubusercontent.com/484670/174650664-5e76674c-1755-496c-ae9b-9ba3d4edc704.png)

I was wondering how hard it would be to support a dark-mode friendly report, eventually by requiring opt-in from the user through the Action public API, ie providing another input like

```yaml
      - name: Setup telemetry for build machine
        uses: thundra-io/workflow-telemetry-action@v1.3.1
        with:
          theme: 'dark' 
```

and using such an input to disambiguate the colors to inject in the payload to be sent to `globadge` under the hood 👀

Thanks in advance for reading/considering this feature request 🙂

**Comment by suleymanbarman** [comment]
Hi @ubiratansoares,

Thanks for your feedback. We're bringing telemetry and much more to the Foresight screen, soon and user theme option is a great idea, could be available before them.

**Comment by serkan-ozal** [comment]
Hi @ubiratansoares,

I have added dark mode support over `theme` input option as you suggested:
```yml
     - name: Collect Workflow Telemetry
        uses: thundra-io/workflow-telemetry-action@v1
        with:
          theme: dark
```

The new version has just been released and `v1` tag re-mapped to it as latest. 

**Note:** It is better to use action over `v1` tag (`thundra-io/workflow-telemetry-action@v1`) instead of specific version tag so you will get latest improvements and fixes automatically.
